### ISSUE TITLE
Why Glaz?

### ISSUE THREAD

**Issue by bistcuite** [glaz-lang/glaz#2]
Hi, why glaz ? What's different between glaz and other languages?

**Comment by 0verse** [comment]
I,m not the creator but as far as I have understood it, glaz is an excellent design based on rust, go and v programming languages with an easy syntax and it is soon to be self-hosted.

**Comment by bistcuite** [comment]
The glaz's syntax is similar to rust and v and these languages have a hard syntax.

**Comment by 0verse** [comment]
V has far mor easier syntax than rust but it is not stable yet. Rust on the other hand has a  learning curve that is very frustrating sometimes. I am reading the rust book and I am lost there while I read some of the source code for the glaz self-hosted compiler and I seem to understand it mostly.

**Comment by bistcuite** [comment]
I think swift's syntax is better for inspiration instead of rust and v.

**Comment by StunxFS** [comment]
The difference between Glaz and the other languages ​​is that Glaz tries to be simple, easy and light, useful for developing video games and desktop apps with a high-level, cross-platform language that does not require much programming knowledge. In conclusion, Glaz is the embodiment of my thinking about what an ideal and safe high-level programming language should look like.﻿
